import os
import json
import asyncio
import warnings
from typing import List, Optional
from pydantic import BaseModel, Field, ValidationError
from dotenv import load_dotenv

# Suppress deprecated google.generativeai FutureWarning
warnings.filterwarnings("ignore", category=FutureWarning, module="google.generativeai")

# Specific imports for dynamic LLM routing
import google.generativeai as genai
from openai import AsyncOpenAI

# Initialize environment variables to securely route API keys
load_dotenv()

# ====================================================================================
# PHASE 3: DETERMINISTIC PYDANTIC SCHEMAS
# ====================================================================================

class QuantitativeSetup(BaseModel):
    """
    Schema representing the inbound payload generated by the Phase 2 data/scanner.py module.
    Enforces strict typing for the vectorized mathematical data.
    """
    ticker: str
    market_regime: str
    current_price: float
    dynamic_atr: float

class AIValidationResponse(BaseModel):
    """
    Strict schema enforcing the outbound structural response of the LLM inference engine.
    This guarantees downstream modules receive deterministic data free of hallucinations.
    """
    execute_trade: bool = Field(description="Final binary decision authorizing the execution engine.")
    asset_ticker: str = Field(description="The precise cryptocurrency ticker evaluated.")
    conviction_score: float = Field(ge=1.0, le=10.0, description="AI confidence score for the setup (1.0=minimum confidence/rejection, 10.0=maximum confidence). MUST be between 1.0 and 10.0, never below 1.0.")
    entry_price: float = Field(description="The precise limit order entry price.")
    stop_loss: float = Field(description="The stop loss price, calculated strictly as Entry +/- (1.5 * dynamic_atr).")
    fractional_tps: List[float] = Field(description="List containing precisely two take-profit levels.")
    compliance_proof: str = Field(description="Mathematical proof demonstrating 20% consistency and 3% drawdown compliance.")

# ====================================================================================
# PHASE 3: ARTIFICIAL INTELLIGENCE ORCHESTRATOR
# ====================================================================================

class AIOrchestrator:
    def __init__(self, model_provider="gemini"):
        """
        Initializes the asynchronous client.
        Defaults to the highly accessible free-tier Google Gemini model, with DeepSeek as a fallback.
        """
        self.model_provider = model_provider.lower()
        
        if self.model_provider == "gemini":
            self.api_key = os.getenv("GEMINI_API_KEY")
            if not self.api_key:
                raise EnvironmentError("CRITICAL HALT: GEMINI_API_KEY not found in.env scope.")
            
            # Configure standard Google Generative AI SDK
            genai.configure(api_key=self.api_key)
            # Utilizing the 2.5-flash model which provides 15 RPM for free tier users in 2026
            self.model = genai.GenerativeModel('gemini-2.5-flash', 
                                              generation_config={"response_mime_type": "application/json",
                                                                 "temperature": 0.15})
            
        elif self.model_provider == "deepseek":
            self.api_key = os.getenv("DEEPSEEK_API_KEY")
            if not self.api_key:
                raise EnvironmentError("CRITICAL HALT: DEEPSEEK_API_KEY not found in.env scope.")
                
            self.client = AsyncOpenAI(
                api_key=self.api_key,
                base_url="https://api.deepseek.com",
                timeout=45.0
            )
            self.model_id = "deepseek-chat"
        else:
            raise ValueError("Unsupported Model Provider. Designation must be 'gemini' or 'deepseek'.")

    def _generate_system_prompt(self) -> str:
        """
        Constructs the high-density Prop Firm Compliance Auditor and Narrative Ranker prompt.
        Embeds the draconian Maven Trading rules directly into the context window.
        """
        return """
        Role: You are an elite cryptocurrency swing trading quantitative portfolio manager and strict Risk Management Auditor operating within a proprietary trading desk.
        
        Mandate: Analyze the provided quantitative market setups, synthesize them against current macro narratives (DePIN, RWA, AI Agents), and guarantee absolute mathematical compliance with institutional constraints.
        
        Account Parameters & Constraints:
        - Baseline Capital: $5,000.00
        - Risk Per Trade: Strictly 0.5% ($25.00)
        - Rule 1: 3% Trailing Drawdown from the absolute highest equity watermark.
        - Rule 2: 1% Maximum Floating Loss across all open trades.
        - Rule 3: 20% Consistency Rule (The single largest winning trade cannot exceed 20% of Total Accrued Profit upon payout request).
        
        Analytical Process (The Consensus):
        1. Eliminate any asset facing impending major supply unlocks, founder distribution, or severe regulatory headwinds within the next 7 days.
        2. Assess the technical safety of the entry based on the provided dynamic_atr value.
        3. Calculate the technical Stop Loss precisely at a 1.5x ATR distance from the Entry Price.
        4. Calculate Fractional Take Profits at 2.0x ATR (TP1) and 3.5x ATR (TP2). This artificially fragments the winning trade, suppressing the magnitude of a single win to safely bypass the 20% consistency trap.
        
        Output Constraint: 
        You MUST return your entire response as a perfectly formatted JSON object.
        The JSON object must strictly adhere to the following schema keys:
        {
            "execute_trade": boolean,
            "asset_ticker": string,
            "conviction_score": float (CRITICAL: Must be between 1.0 and 10.0. Use 1.0 for minimal/borderline confidence, 10.0 for maximum. NEVER use 0.0 or values below 1.0. If rejecting a setup, set execute_trade to false AND conviction_score to 1.0),
            "entry_price": float,
            "stop_loss": float,
            "fractional_tps": [float, float],
            "compliance_proof": string
        }
        Do not output any markdown formatting, preamble, or conversational text outside of the JSON object.
        """

    async def generate_optimal_setup(self, setups: List[dict]) -> Optional:
        """
        Transmits the filtered quantitative arrays to the LLM for contextual synthesis.
        Enforces strict JSON object parsing and Pydantic validation upon payload receipt.
        """
        if not setups:
            print("Notice: No valid setups provided to the AI layer. Maintaining cash posture.")
            return None

        # Format the inbound setups into a structured text string for API ingestion
        setup_data_string = json.dumps(setups, indent=2)
        system_instruction = self._generate_system_prompt()
        user_prompt = f"{system_instruction}\n\nAnalyze the following valid market setups and identify the single highest probability trade adhering to the constraints. Ensure the output is strictly valid json:\n\n{setup_data_string}"

        print(f"Transmitting quantitative payloads to {self.model_provider.upper()} inference engine...")

        try:
            raw_content = ""
            
            # Execute Gemini Async Request
            if self.model_provider == "gemini":
                response = await self.model.generate_content_async(user_prompt)
                raw_content = response.text
                
            # Execute DeepSeek Fallback Async Request
            elif self.model_provider == "deepseek":
                messages = [
                    {"role": "system", "content": system_instruction},
                    {"role": "user", "content": user_prompt}
                ]
                response = await self.client.chat.completions.create(
                    model=self.model_id,
                    messages=messages,
                    temperature=0.15, 
                    response_format={'type': 'json_object'}
                )
                raw_content = response.choices[0].message.content
            
            # Parse the raw string into a deterministic Python dictionary
            parsed_json = json.loads(raw_content)
            
            # Safety fallback: Ensure conviction_score is >= 1.0
            if "conviction_score" in parsed_json and parsed_json["conviction_score"] < 1.0:
                print(f"Warning: LLM returned conviction_score {parsed_json['conviction_score']} (below 1.0). Correcting to 1.0")
                parsed_json["conviction_score"] = 1.0
            
            # Enforce the strict Pydantic schema validation
            validated_response = AIValidationResponse(**parsed_json)
            
            print(f"AI Synthesis Complete. Executable Logic Generated for: {validated_response.asset_ticker}")
            return validated_response
            
        except json.JSONDecodeError as e:
            print(f"CRITICAL ERROR: LLM failed to return a valid JSON object. Parsing aborted. Error: {e}\nRaw Output: {raw_content}")
            return None
        except ValidationError as e:
            print(f"CRITICAL ERROR: LLM output violated the Pydantic structural schema. Halting execution. Error: {e}")
            return None
        except Exception as e:
            print(f"NETWORK ERROR: API communication failure or timeout. Error: {e}")
            return None

# ====================================================================================
# PHASE 3: ISOLATED DIAGNOSTIC HARNESS
# ====================================================================================
if __name__ == "__main__":
    async def run_diagnostics():
        # Mock payload representing the raw output from Phase 2 (data/scanner.py)
        # Simulates realistic MarketScanner results with multi-asset confluences
        mock_scanner_output = [
            {
                "symbol": "SOL/USDT",
                "regime": "BEARISH",
                "current_price": 142.50,
                "atr": 8.45
            },
            {
                "symbol": "ETH/USDT",
                "regime": "BEARISH",
                "current_price": 2003.84,
                "atr": 135.07
            },
            {
                "symbol": "XRP/USDT",
                "regime": "BEARISH",
                "current_price": 1.39,
                "atr": 0.0979
            }
        ]
        
        # Instantiate the orchestrator (Requires GEMINI_API_KEY in .env)
        try:
            ai_agent = AIOrchestrator(model_provider="gemini")
            result = await ai_agent.generate_optimal_setup(mock_scanner_output)
            
            if result and result.execute_trade:
                print("\n--- VALIDATED EXECUTION PAYLOAD ---")
                print(f"Target Asset:   {result.asset_ticker}")
                print(f"Conviction:     {result.conviction_score}/10.0")
                print(f"Entry Price:    ${result.entry_price}")
                print(f"Stop Loss:      ${result.stop_loss}")
                print(f"Take Profits:   {result.fractional_tps}")
                print(f"Audit Proof:    {result.compliance_proof}")
            else:
                print("\nAI System rejected all setups based on fundamental risk constraints.")
                
        except EnvironmentError as env_err:
            print(f"Workspace Setup Error: {env_err}")

    # Execute the asynchronous test loop
    asyncio.run(run_diagnostics())
